// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuV3SPbMQVwIuyOEMXz4RhoncRzk-9b4A',
    appId: '1:103225055326:web:d64c125c6ab1484a44fccf',
    messagingSenderId: '103225055326',
    projectId: 'avocado-flutter',
    authDomain: 'avocado-flutter.firebaseapp.com',
    storageBucket: 'avocado-flutter.appspot.com',
    measurementId: 'G-952WEEFS3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABowx6_WRqHlMY8kooI1_ISvHvpuH_78',
    appId: '1:103225055326:android:3387f623100e381344fccf',
    messagingSenderId: '103225055326',
    projectId: 'avocado-flutter',
    storageBucket: 'avocado-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGTRY5tdFhjVuIcFoRk4EIp8fgulbN6ak',
    appId: '1:103225055326:ios:0608f081a4ccfbdd44fccf',
    messagingSenderId: '103225055326',
    projectId: 'avocado-flutter',
    storageBucket: 'avocado-flutter.appspot.com',
    iosClientId: '103225055326-3500it6af9r7n47orka16hhtjamks15d.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGTRY5tdFhjVuIcFoRk4EIp8fgulbN6ak',
    appId: '1:103225055326:ios:0608f081a4ccfbdd44fccf',
    messagingSenderId: '103225055326',
    projectId: 'avocado-flutter',
    storageBucket: 'avocado-flutter.appspot.com',
    iosClientId: '103225055326-3500it6af9r7n47orka16hhtjamks15d.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocado',
  );
}
